package com.auralauncher.app.backup

import com.auralauncher.app.data.*
import org.json.JSONArray
import org.json.JSONObject

/**
 * Full-configuration backup — grid layout (including the dock, which
 * shares the same table under a reserved page number), folders, focus
 * modes, icon shape overrides, and app settings.
 *
 * Hosted widgets are exported for the record but NOT restored: a widget's
 * appWidgetId is a binding issued by AppWidgetHost on a specific device/
 * install — it isn't portable to a fresh install or another device, so
 * re-inserting old IDs would just create broken, unresponsive widget
 * cells. The honest thing is to tell the user to re-add widgets manually
 * after a restore rather than silently produce something that looks
 * restored but doesn't work.
 */
object BackupService {

    suspend fun export(dao: LauncherDao, settingsJson: JSONObject): String {
        val root = JSONObject()

        root.put("gridItems", JSONArray(dao.getAllGridItemsOnce().map { item ->
            JSONObject().apply {
                put("page", item.page); put("row", item.row); put("col", item.col); put("packageName", item.packageName)
            }
        }))

        root.put("folders", JSONArray(dao.getAllFoldersOnce().map { f ->
            JSONObject().apply { put("id", f.id); put("page", f.page); put("row", f.row); put("col", f.col); put("name", f.name) }
        }))

        root.put("folderMembers", JSONArray(dao.getAllFolderMembersOnce().map { m ->
            JSONObject().apply { put("packageName", m.packageName); put("folderId", m.folderId) }
        }))

        root.put("focusModes", JSONArray(dao.getAllFocusModesOnce().map { fm ->
            JSONObject().apply {
                put("name", fm.name); put("allowedPackages", JSONArray(fm.allowedPackages)); put("isActive", fm.isActive)
            }
        }))

        root.put("iconOverrides", JSONArray(dao.getAllIconOverridesOnce().map { o ->
            JSONObject().apply { put("packageName", o.packageName); put("shape", o.shape.name) }
        }))

        // Informational only — see class doc. Not restored.
        root.put("hostedWidgetsInfoOnly", JSONArray(dao.getAllHostedWidgetsOnce().map { w ->
            JSONObject().apply { put("page", w.page); put("row", w.row); put("col", w.col) }
        }))

        root.put("settings", settingsJson)
        return root.toString(2)
    }

    /** Wipes current grid/folders/focus-modes/icon-overrides and replaces
     *  them with what's in [json]. Settings are returned separately so the
     *  caller (which owns the SharedPreferences-backed settings managers)
     *  can apply them without this object needing to know about every
     *  settings manager individually. */
    suspend fun import(json: String, dao: LauncherDao): JSONObject {
        val root = JSONObject(json)

        dao.clearAllGridItems()
        dao.clearAllFolders()
        dao.clearAllFolderMembers()
        dao.clearAllFocusModes()
        dao.clearAllIconOverrides()

        val gridItems = root.optJSONArray("gridItems") ?: JSONArray()
        for (i in 0 until gridItems.length()) {
            val o = gridItems.getJSONObject(i)
            dao.upsertGridItem(GridItemEntity(o.getInt("page"), o.getInt("row"), o.getInt("col"), o.getString("packageName")))
        }

        val folders = root.optJSONArray("folders") ?: JSONArray()
        val folderIdRemap = mutableMapOf<Long, Long>() // old id -> new autogenerated id
        for (i in 0 until folders.length()) {
            val o = folders.getJSONObject(i)
            val oldId = o.getLong("id")
            val newId = dao.upsertFolder(FolderEntity(page = o.getInt("page"), row = o.getInt("row"), col = o.getInt("col"), name = o.getString("name")))
            folderIdRemap[oldId] = newId
        }

        val folderMembers = root.optJSONArray("folderMembers") ?: JSONArray()
        for (i in 0 until folderMembers.length()) {
            val o = folderMembers.getJSONObject(i)
            val oldFolderId = o.getLong("folderId")
            val remapped = folderIdRemap[oldFolderId] ?: continue
            dao.upsertFolderMember(FolderMemberEntity(o.getString("packageName"), remapped))
        }

        val focusModes = root.optJSONArray("focusModes") ?: JSONArray()
        for (i in 0 until focusModes.length()) {
            val o = focusModes.getJSONObject(i)
            val packagesArray = o.getJSONArray("allowedPackages")
            val packages = (0 until packagesArray.length()).map { packagesArray.getString(it) }
            dao.upsertFocusMode(FocusModeEntity(name = o.getString("name"), allowedPackages = packages, isActive = o.optBoolean("isActive", false)))
        }

        val iconOverrides = root.optJSONArray("iconOverrides") ?: JSONArray()
        for (i in 0 until iconOverrides.length()) {
            val o = iconOverrides.getJSONObject(i)
            val shape = runCatching { IconShape.valueOf(o.getString("shape")) }.getOrDefault(IconShape.SYSTEM_DEFAULT)
            dao.upsertIconOverride(IconOverrideEntity(o.getString("packageName"), shape))
        }

        return root.optJSONObject("settings") ?: JSONObject()
    }
}
